name: OctoBot-Pro-CI
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    uses: Drakkar-Software/.github/.github/workflows/python3_lint_workflow.yml@master
    with:
      project_main_package: octobot_pro

  tests:
    name: ${{ matrix.os }} - Python - ${{ matrix.type }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        type: [ sources ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
          architecture: x64

      - name: Install dependencies
        run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

      - name: Pytests
        run: pytest -s --durations=0 -rw tests

  publish:
    needs: tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    uses: Drakkar-Software/.github/.github/workflows/python3_wheel_workflow.yml@master
    with:
      use_cython: false
    secrets:
      PYPI_OFFICIAL_UPLOAD_URL: ${{ secrets.PYPI_OFFICIAL_UPLOAD_URL }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  notify:
    if: ${{ failure() }}
    needs:
      - lint
      - tests
      - publish
    uses: Drakkar-Software/.github/.github/workflows/failure_notify_workflow.yml@master
    secrets:
      DISCORD_GITHUB_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
